
project_id = "aeuxszpcuoqcbcynyrpo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false
enable_phone_confirmations = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.ai-compliance-assistant]
verify_jwt = false

[functions.analyze-contract-compliance]
verify_jwt = false
