// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeuxszpcuoqcbcynyrpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFldXhzenBjdW9xY2JjeW55cnBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTgwNzMsImV4cCI6MjA2NzIzNDA3M30.izwkDlwUIRo2kF9eI3N0c_aI_kJQo3G9XODdrvVjIgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});